In [23]:
import os
import pandas as pd
# os.environ['HTA_DISABLE_NS_ROUNDING'] = '1'
# os.environ['CRITICAL_PATH_ADD_ZERO_WEIGHT_LAUNCH_EDGE'] = '1'
from hta.trace_analysis import TraceAnalysis
base_dir = "/mnt/self-define/zhangweixing/profiler_log/deepseek_v2/tensorboard/"
# trace_dir = base_dir + "20250325-1043_pretrain-zjmcore-dsv3-16B-lr-4E-5-minlr-4E-6-bs-1-gbs-32-seqlen-4096-pr-bf16-pp-2-ac-none/"
trace_dir = base_dir + "suhui/exp2/"

analyzer = TraceAnalysis(trace_dir=trace_dir)
rank=0

Parsed /mnt/self-define/zhangweixing/profiler_log/deepseek_v2/tensorboard/suhui/exp2/NH-DC-NM129-G06-28U-GPU-184_2735765.1747015681428304870.pt.trace.json time = 1.54 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed /mnt/self-define/zhangweixing/profiler_log/deepseek_v2/tensorboard/suhui/exp2/NH-DC-NM129-G06-28U-GPU-184_2735765.1747015681428304870.pt.trace.json backend=json in 3.01 seconds; current PID:18251
Overall parsing of /mnt/self-define/zhangweixing/profiler_log/deepseek_v2/tensorboard/suhui/exp2/NH-DC-NM129-G06-28U-GPU-184_2735765.1747015681428304870.pt.trace.json in 3.30 seconds; current PID:18251
leaving parse_multiple_ranks duration=3.35 seconds
leaving parse_traces duration=3.35 seconds
There is only one iteration in the trace. The analysis result may not be accurate.

## 统计整体时间分布

In [26]:
temporal_breakdown_df = analyzer.get_temporal_breakdown(visualize=False)
temporal_breakdown_df

,rank,idle_time(us),compute_time(us),non_compute_time(us),kernel_time(us),idle_time_pctg,compute_time_pctg,non_compute_time_pctg
0,0,448851781.0,341779601.0,2.847655e+09,3.638287e+09,12.34,9.39,78.27

In [27]:
kernel_type_metrics_df, kernel_metrics_df = analyzer.get_gpu_kernel_breakdown(visualize=False)
kernel_type_metrics_df

/mnt/self-define/zhangweixing/code/HolisticTraceAnalysis/hta/analyzers/breakdown_analysis.py:518: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kernel_t_df.melt(var_name="status", value_name="time").replace(
/mnt/self-define/zhangweixing/code/HolisticTraceAnalysis/hta/analyzers/breakdown_analysis.py:518: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kernel_t_df.melt(var_name="status", value_name="time").replace(
/mnt/self-define/zhangweixing/code/HolisticTraceAnalysis/hta/analyzers/breakdown_analysis.py:518: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kernel_t_df.melt(var_name="status", value_name="time").replace(

                      kernel_type         sum  percentage
0                   COMMUNICATION  2844736998        89.2
1                     COMPUTATION   341775281        10.7
2                          MEMORY     2918222         0.1
3  COMPUTATION overlapping MEMORY        4320         0.0

In [ ]:
kernel_metrics_df

In [ ]:
overlap_df = analyzer.get_comm_comp_overlap(visualize=False)
overlap_df

In [ ]:
idle_time_df, _ = analyzer.get_idle_time_breakdown(ranks=[rank], visualize=False)
idle_time_df

## 按用户标签统计时间

In [12]:
user_annotation_temporal_breakdown, _ = analyzer.get_user_annotation_temporal_breakdown()
with pd.option_context("display.max_columns", None, "display.max_rows", None):
    display(user_annotation_temporal_breakdown)

combined,rank,full_iteration,forward_compute,backward_compute,optimizer_step,forward_data_process,forward_model_compute,forward_loss_compute,mla_forward,moe_routing,moe_token_perm,moe_expert_compute,moe_token_unperm,mla_qkv_gen,mla_inference_adjust,mla_attention,mla_output,moe_router_input_jitter,moe_router_gating,moe_router_routing,experts_te_grouped_mlp_fc1,experts_te_grouped_mlp_activation,experts_te_grouped_mlp_fc2,backward_grad_prep,backward_model_compute,backward_grad_collect,ProfilerStep#10,nccl:coalesced,comm_send_forward_recv_backward,comm_send_forward,comm_recv_forward,moe_shared_expert,experts_shared_expert_forward,backward_comm_alltoall_backward,backward_comm_alltoall_forward,comm_alltoall_forward,mlp_fc1,mlp_fc2,comm_gather_from_sequence_parallel_region_forward,nccl:all_to_all,mlp_activation,backward_nccl:all_to_all,backward_comm_gather_from_sequence_parallel_region_backward,nccl:_all_gather_base,finalize_grads,dp_allreduce_grads,backward_comm_gather_from_model_parallel_region_backward,Optimizer.step#FusedAdam.step,comm_gather_from_model_parallel_region_forward,nccl:all_reduce,nccl:broadcast,enumerate#_MultiProcessingDataLoaderIter.__next__,nccl:all_gather_into_tensor_coalesced,comm_reduce_from_model_parallel_region_forward,nccl:reduce_scatter_tensor_coalesced,backward_comm_reduce_from_model_parallel_region_backward,comm_send_backward,grad_sync_enable,evaluation_step,comm_send_backward_recv_forward,grad_sync_disable
0,7,3795.198797,888.65938,544.058201,680.349,0.215668,888.071555,0.194949,164.280558,100.47065,287.159196,72.633017,160.275469,106.816083,1.203654,37.23548,15.4865,1.175167,6.08865,89.832499,30.974815,7.152496,30.577675,0.107485,543.358173,0.318709,5323.163647,1958.258202,1054.555403,531.189856,374.604532,40.060774,35.690534,31.917284,24.938698,24.804767,15.332829,13.918457,13.423329,7.137528,6.843754,6.499958,3.396217,3.048734,2.503894,2.467315,1.998517,1.91748,1.818577,0.583129,0.252133,0.227365,0.153938,0.133398,0.126467,0.106151,0.075986,0.060255,0.059864,0.057034,0.055749
1,Average,3795.198797,888.65938,544.058201,680.349,0.215668,888.071555,0.194949,164.280558,100.47065,287.159196,72.633017,160.275469,106.816083,1.203654,37.23548,15.4865,1.175167,6.08865,89.832499,30.974815,7.152496,30.577675,0.107485,543.358173,0.318709,5323.163647,1958.258202,1054.555403,531.189856,374.604532,40.060774,35.690534,31.917284,24.938698,24.804767,15.332829,13.918457,13.423329,7.137528,6.843754,6.499958,3.396217,3.048734,2.503894,2.467315,1.998517,1.91748,1.818577,0.583129,0.252133,0.227365,0.153938,0.133398,0.126467,0.106151,0.075986,0.060255,0.059864,0.057034,0.055749

## 通信时间统计
### comm_kernel_info是所有在GPU设备上的通信时间

In [25]:
comm_kernel_info = analyzer.get_launch_comm_kernels_with_user_annotations(rank=rank, no_overlap=False)
comm_kernel_info.groupby(['tid_cpu','s_user_annotation_cpu']).agg(
    dur_gpu_sum=('dur_gpu', lambda x: x.sum() / 1000),
    count=('dur_gpu', 'count')
).groupby('tid_cpu').apply(lambda x: x.sort_values(by='dur_gpu_sum', ascending=False))

                                                                   dur_gpu_sum  \
tid_cpu tid_cpu s_user_annotation_cpu
2735765 2735765 ProfilerStep#10                                    2592693.341
                full_iteration                                     1684854.069
                nccl:coalesced                                     1301238.164
                comm_recv_forward                                  1190517.517
                nccl:all_reduce                                     809644.917
                optimizer_step                                      540314.708
                forward_compute                                     350652.711
                forward_model_compute                               350652.711
                nccl:all_to_all                                     237726.450
                comm_alltoall_forward                               237726.450
                moe_token_perm                                      224137.690
                nccl:_all_gather_base                               178311.661
                moe_token_unperm                                    126515.021
                comm_gather_from_sequence_parallel_region_forward   112926.261
                comm_send_forward                                   110720.647
                nccl:all_gather_into_tensor_coalesced                32974.298
                finalize_grads                                       32963.194
                dp_allreduce_grads                                   32963.194
                nccl:reduce_scatter_tensor_coalesced                 32797.851
2765913 2765913 comm_alltoall_backward                              252043.657
                comm_alltoall_forward                               252043.657
                nccl:all_to_all                                     252043.657

                                                                   count
tid_cpu tid_cpu s_user_annotation_cpu
2735765 2735765 ProfilerStep#10                                       58
                full_iteration                                        46
                nccl:coalesced                                         2
                comm_recv_forward                                      1
                nccl:all_reduce                                        9
                optimizer_step                                         6
                forward_compute                                       42
                forward_model_compute                                 42
                nccl:all_to_all                                       28
                comm_alltoall_forward                                 28
                moe_token_perm                                        28
                nccl:_all_gather_base                                 16
                moe_token_unperm                                      14
                comm_gather_from_sequence_parallel_region_forward     14
                comm_send_forward                                      1
                nccl:all_gather_into_tensor_coalesced                  2
                finalize_grads                                         2
                dp_allreduce_grads                                     2
                nccl:reduce_scatter_tensor_coalesced                   1
2765913 2765913 comm_alltoall_backward                                28
                comm_alltoall_forward                                 28
                nccl:all_to_all                                       28

### comm_kernel_info_not_overlap是统计没有被计算掩盖的通信时间分布情况

In [28]:
comm_kernel_info_not_overlap = analyzer.get_launch_comm_kernels_with_user_annotations(rank=rank, no_overlap=True)
comm_kernel_info_not_overlap.groupby(['tid_cpu','s_user_annotation_cpu']).agg(
    dur_gpu_sum=('dur_gpu', lambda x: x.sum() / 1000),
    count=('dur_gpu', 'count')
).groupby('tid_cpu').apply(lambda x: x.sort_values(by='dur_gpu_sum', ascending=False))

                                                                   dur_gpu_sum  \
tid_cpu tid_cpu s_user_annotation_cpu
2735765 2735765 ProfilerStep#10                                    2592693.341
                full_iteration                                     1684854.069
                nccl:coalesced                                     1301238.164
                comm_recv_forward                                  1190517.517
                nccl:all_reduce                                     809644.917
                optimizer_step                                      540314.708
                forward_compute                                     350652.711
                forward_model_compute                               350652.711
                nccl:all_to_all                                     237726.450
                comm_alltoall_forward                               237726.450
                moe_token_perm                                      224137.690
                nccl:_all_gather_base                               178311.661
                moe_token_unperm                                    126515.021
                comm_gather_from_sequence_parallel_region_forward   112926.261
                comm_send_forward                                   110720.647
                nccl:all_gather_into_tensor_coalesced                32974.298
                finalize_grads                                       32963.194
                dp_allreduce_grads                                   32963.194
                nccl:reduce_scatter_tensor_coalesced                 32797.851
2765913 2765913 comm_alltoall_backward                              252043.657
                comm_alltoall_forward                               252043.657
                nccl:all_to_all                                     252043.657

                                                                   count
tid_cpu tid_cpu s_user_annotation_cpu
2735765 2735765 ProfilerStep#10                                       58
                full_iteration                                        46
                nccl:coalesced                                         2
                comm_recv_forward                                      1
                nccl:all_reduce                                        9
                optimizer_step                                         6
                forward_compute                                       42
                forward_model_compute                                 42
                nccl:all_to_all                                       28
                comm_alltoall_forward                                 28
                moe_token_perm                                        28
                nccl:_all_gather_base                                 16
                moe_token_unperm                                      14
                comm_gather_from_sequence_parallel_region_forward     14
                comm_send_forward                                      1
                nccl:all_gather_into_tensor_coalesced                  2
                finalize_grads                                         2
                dp_allreduce_grads                                     2
                nccl:reduce_scatter_tensor_coalesced                   1
2765913 2765913 comm_alltoall_backward                                28
                comm_alltoall_forward                                 28
                nccl:all_to_all                                       28